// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resturant_Project.Data;

#nullable disable

namespace Restaurant_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815125414_Addseeddata")]
    partial class Addseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resturant_Project.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Main Courses"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Pizza"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Burgers"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Pasta"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CategoryId = 1,
                            Description = "Crispy chicken wings served with our special sauce.",
                            Name = "Chicken Wings",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 2,
                            CategoryId = 1,
                            Description = "Crispy mozzarella sticks served with tomato sauce.",
                            Name = "Mozzarella Sticks",
                            Price = 150m
                        },
                        new
                        {
                            MenuItemId = 3,
                            CategoryId = 1,
                            Description = "Fresh bread with garlic, butter and herbs.",
                            Name = "Garlic Bread",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 4,
                            CategoryId = 2,
                            Description = "Juicy grilled chicken breast served with rice and vegetables.",
                            Name = "Grilled Chicken",
                            Price = 280m
                        },
                        new
                        {
                            MenuItemId = 5,
                            CategoryId = 2,
                            Description = "Tender grilled beef steak served with vegetables and fries.",
                            Name = "Beef Steak",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 6,
                            CategoryId = 2,
                            Description = "Grilled chicken with creamy Alfredo sauce and pasta.",
                            Name = "Chicken Alfredo",
                            Price = 260m
                        },
                        new
                        {
                            MenuItemId = 7,
                            CategoryId = 3,
                            Description = "Classic pizza with tomato sauce, mozzarella and fresh basil.",
                            Name = "Margherita Pizza",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 8,
                            CategoryId = 3,
                            Description = "Pizza topped with grilled chicken, mozzarella and vegetables.",
                            Name = "Chicken Pizza",
                            Price = 230m
                        },
                        new
                        {
                            MenuItemId = 9,
                            CategoryId = 3,
                            Description = "Classic pizza topped with pepperoni and mozzarella cheese.",
                            Name = "Pepperoni Pizza",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 10,
                            CategoryId = 4,
                            Description = "Juicy beef burger with lettuce, tomato, onion and special sauce.",
                            Name = "Classic Beef Burger",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 11,
                            CategoryId = 4,
                            Description = "Crispy chicken burger with lettuce, cheese and special sauce.",
                            Name = "Chicken Burger",
                            Price = 190m
                        },
                        new
                        {
                            MenuItemId = 12,
                            CategoryId = 4,
                            Description = "Beef burger topped with melted cheddar cheese.",
                            Name = "Cheese Burger",
                            Price = 240m
                        },
                        new
                        {
                            MenuItemId = 13,
                            CategoryId = 5,
                            Description = "Spaghetti pasta with rich beef tomato sauce.",
                            Name = "Spaghetti Bolognese",
                            Price = 210m
                        },
                        new
                        {
                            MenuItemId = 14,
                            CategoryId = 5,
                            Description = "Fettuccine pasta with creamy Alfredo sauce and parmesan.",
                            Name = "Fettuccine Alfredo",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 15,
                            CategoryId = 5,
                            Description = "Penne pasta with spicy tomato sauce and herbs.",
                            Name = "Penne Arrabbiata",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 16,
                            CategoryId = 6,
                            Description = "Rich and moist chocolate cake served with chocolate sauce.",
                            Name = "Chocolate Cake",
                            Price = 130m
                        },
                        new
                        {
                            MenuItemId = 17,
                            CategoryId = 6,
                            Description = "Creamy cheesecake served with strawberry sauce.",
                            Name = "Cheesecake",
                            Price = 140m
                        },
                        new
                        {
                            MenuItemId = 18,
                            CategoryId = 6,
                            Description = "Three scoops of your favorite ice cream flavors.",
                            Name = "Ice Cream",
                            Price = 100m
                        },
                        new
                        {
                            MenuItemId = 19,
                            CategoryId = 7,
                            Description = "Freshly squeezed orange juice.",
                            Name = "Fresh Orange Juice",
                            Price = 80m
                        },
                        new
                        {
                            MenuItemId = 20,
                            CategoryId = 7,
                            Description = "Chilled soft drink.",
                            Name = "Cola",
                            Price = 50m
                        },
                        new
                        {
                            MenuItemId = 21,
                            CategoryId = 7,
                            Description = "Fresh mango juice served chilled.",
                            Name = "Mango Juice",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Resturant_Project.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Resturant_Project.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.HasOne("Resturant_Project.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Resturant_Project.Models.OrderItem", b =>
                {
                    b.HasOne("Resturant_Project.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resturant_Project.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Resturant_Project.Models.Payment", b =>
                {
                    b.HasOne("Resturant_Project.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Resturant_Project.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Resturant_Project.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
