// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resturant_Project.Data;

#nullable disable

namespace Restaurant_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Resturant_Project.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Main Courses"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Pizza"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Burgers"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Pasta"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CategoryId = 1,
                            Description = "Crispy chicken wings served with our special sauce.",
                            ImageUrl = "/img/chicken wings food.jfif",
                            Name = "Chicken Wings",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 2,
                            CategoryId = 1,
                            Description = "Crispy mozzarella sticks served with tomato sauce.",
                            ImageUrl = "/img/mozzarella sticks.jfif",
                            Name = "Mozzarella Sticks",
                            Price = 150m
                        },
                        new
                        {
                            MenuItemId = 3,
                            CategoryId = 1,
                            Description = "Fresh bread with garlic, butter and herbs.",
                            ImageUrl = "/img/garlic bread.jfif",
                            Name = "Garlic Bread",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 4,
                            CategoryId = 2,
                            Description = "Juicy grilled chicken breast served with rice and vegetables.",
                            ImageUrl = "/img/grilled chicken.jfif",
                            Name = "Grilled Chicken",
                            Price = 280m
                        },
                        new
                        {
                            MenuItemId = 5,
                            CategoryId = 2,
                            Description = "Tender grilled beef steak served with vegetables and fries.",
                            ImageUrl = "/img/beef steak fries.jfif",
                            Name = "Beef Steak",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 6,
                            CategoryId = 2,
                            Description = "Grilled chicken with creamy Alfredo sauce and pasta.",
                            ImageUrl = "/img/chicken alfredo pasta.jfif",
                            Name = "Chicken Alfredo",
                            Price = 260m
                        },
                        new
                        {
                            MenuItemId = 7,
                            CategoryId = 3,
                            Description = "Classic pizza with tomato sauce, mozzarella and fresh basil.",
                            ImageUrl = "/img/margherita pizza.jfif",
                            Name = "Margherita Pizza",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 8,
                            CategoryId = 3,
                            Description = "Pizza topped with grilled chicken, mozzarella and vegetables.",
                            ImageUrl = "/img/chicken pizza.jfif",
                            Name = "Chicken Pizza",
                            Price = 230m
                        },
                        new
                        {
                            MenuItemId = 9,
                            CategoryId = 3,
                            Description = "Classic pizza topped with pepperoni and mozzarella cheese.",
                            ImageUrl = "/img/pepperoni pizza.jfif",
                            Name = "Pepperoni Pizza",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 10,
                            CategoryId = 4,
                            Description = "Juicy beef burger with lettuce, tomato, onion and special sauce.",
                            ImageUrl = "/img/classic beef burger.jfif",
                            Name = "Classic Beef Burger",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 11,
                            CategoryId = 4,
                            Description = "Crispy chicken burger with lettuce, cheese and special sauce.",
                            ImageUrl = "/img/crispy chicken burger.jfif",
                            Name = "Chicken Burger",
                            Price = 190m
                        },
                        new
                        {
                            MenuItemId = 12,
                            CategoryId = 4,
                            Description = "Beef burger topped with melted cheddar cheese.",
                            ImageUrl = "/img/cheeseburger.jfif",
                            Name = "Cheese Burger",
                            Price = 240m
                        },
                        new
                        {
                            MenuItemId = 13,
                            CategoryId = 5,
                            Description = "Spaghetti pasta with rich beef tomato sauce.",
                            ImageUrl = "/img/spaghetti bolognese.jfif",
                            Name = "Spaghetti Bolognese",
                            Price = 210m
                        },
                        new
                        {
                            MenuItemId = 14,
                            CategoryId = 5,
                            Description = "Fettuccine pasta with creamy Alfredo sauce and parmesan.",
                            ImageUrl = "/img/fettuccine alfredo.jfif",
                            Name = "Fettuccine Alfredo",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 15,
                            CategoryId = 5,
                            Description = "Penne pasta with spicy tomato sauce and herbs.",
                            ImageUrl = "/img/penne arrabbiata.jfif",
                            Name = "Penne Arrabbiata",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 16,
                            CategoryId = 6,
                            Description = "Rich and moist chocolate cake served with chocolate sauce.",
                            ImageUrl = "/img/chocolate cake.jfif",
                            Name = "Chocolate Cake",
                            Price = 130m
                        },
                        new
                        {
                            MenuItemId = 17,
                            CategoryId = 6,
                            Description = "Creamy cheesecake served with strawberry sauce.",
                            ImageUrl = "/img/cheesecake strawberry.jfif",
                            Name = "Cheesecake",
                            Price = 140m
                        },
                        new
                        {
                            MenuItemId = 18,
                            CategoryId = 6,
                            Description = "Three scoops of your favorite ice cream flavors.",
                            ImageUrl = "/img/ice cream.jfif",
                            Name = "Ice Cream",
                            Price = 100m
                        },
                        new
                        {
                            MenuItemId = 19,
                            CategoryId = 7,
                            Description = "Freshly squeezed orange juice.",
                            ImageUrl = "/img/fresh orange juice.jfif",
                            Name = "Fresh Orange Juice",
                            Price = 80m
                        },
                        new
                        {
                            MenuItemId = 20,
                            CategoryId = 7,
                            Description = "Chilled soft drink.",
                            ImageUrl = "/img/cola glass ice.jfif",
                            Name = "Cola",
                            Price = 50m
                        },
                        new
                        {
                            MenuItemId = 21,
                            CategoryId = 7,
                            Description = "Fresh mango juice served chilled.",
                            ImageUrl = "/img/fresh mango juice glass.jfif",
                            Name = "Mango Juice",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Resturant_Project.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Resturant_Project.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.HasOne("Resturant_Project.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Resturant_Project.Models.OrderItem", b =>
                {
                    b.HasOne("Resturant_Project.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resturant_Project.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Resturant_Project.Models.Payment", b =>
                {
                    b.HasOne("Resturant_Project.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Resturant_Project.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Resturant_Project.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Resturant_Project.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
